vich_uploader:
    db_driver: orm

    mappings:
        user_images: 
            uri_prefix: '%path.users_images%'
            upload_destination: '%kernel.project_dir%/public%path.users_images%'
            